Confess improvements
obiwac/DiscordSINFBot pull request #3
Opened 2023-06-20 15:52 UTC by obiwac

2023-06-20 16:47 UTC, NoaQuenon requested changes

2023-06-20 16:47 UTC, NoaQuenon commented on src/commands/confess.js
>                  await vote.edit({
The editing should be done after sending the confession in the confess channel (the two blocks should be inverted)

2023-06-21 07:55 UTC, Emilevillette commented on src/commands/confess.js
>                  await vote.edit({
should be resolved in [2590894](https://github.com/obiwac/DiscordSINFBot/pull/3/commits/25908945e152444aa240b94f98d84c1d065686fd) , can you review and confirm ?

2023-06-21 16:28 UTC, NoaQuenon approved these changes

2023-06-21 16:28 UTC, NoaQuenon commented on src/commands/confess.js
>                  await vote.edit({
That should be fine

2023-06-21 16:43 UTC, Emilevillette approved these changes
See previous comments.

2023-06-21 16:43 UTC, merged